### ISSUE TITLE
Ignores bluehammer / admins. No matter what any bluehammer's inventory is only partially dropped even though full inventory keeping is on for all users

### ISSUE THREAD

**Issue by S33TH3** [khaiizha/keepinventory#2]

**Comment by khaiizha** [comment]
for the admin/bluehammer, you can put the permission keepinventory.keep and keepinventory.vip or the other 2 (.vvip/.arch) for them and for default player only have keepinventory.keep

**Comment by S33TH3** [comment]
about a month late, we've removed the plugin due to unturned natively allowing you to prevent item dropping via config.json
